name = "Inventario-Florestal"
uuid = "7fe6ee78-c63f-4340-a509-709b64f20cbf"
authors = ["claitonnardini <claitonnardini@live.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
